// apps/vue/src/components/Marker.vue
<script lang="ts" setup>
import { useNaverMap } from "../composables/useNaverMap";
import { ref, useAttrs, watch } from "vue";

const emits = defineEmits<{
  (event: "onLoaded", marker: naver.maps.Marker): void;
}>();
const props = defineProps<{
  latitude: number;
  longitude: number;
  htmlIcon?: naver.maps.HtmlIcon;
}>();

const attrs = useAttrs();
const { getNaverMap } = useNaverMap();
const { mapIsLoaded, map } = getNaverMap();

const marker = ref<naver.maps.Marker>();
const markerRef = ref<HTMLDivElement>();

const getMarkerIcon = () => {
  if (!markerRef.value?.childElementCount) return undefined; // default marker
  return Object.assign({ content: markerRef.value }, props.htmlIcon ?? {});
};
const handleCreateMarker = () => {
  if (!markerRef.value) throw new Error("marker ref is not founded");
  marker.value = new naver.maps.Marker({
    position: new naver.maps.LatLng(props.latitude, props.longitude),
    map: map?.value,
    icon: getMarkerIcon(),
  });
  emits("onLoaded", marker.value);
};

watch(
  () => mapIsLoaded?.value,
  (newVal) => {
    if (!newVal) return;
    handleCreateMarker();
  },
);
</script>

<template>
  <div style="display: none">
    <div ref="markerRef" v-bind="attrs">
      <slot />
    </div>
  </div>
</template>

// apps/react/src/components/Marker.component.tsx
import { useNaverMap } from "@/hooks/useNaverMap";
import { useEffect, useRef, useState } from "react";
import type { PropsWithChildren, HTMLAttributes } from "react";

interface Props extends PropsWithChildren, HTMLAttributes<HTMLDivElement> {
  onLoaded?: (marker: naver.maps.Marker) => void;
  latitude: number;
  longtitude: number;
}

export default function Marker({
  children,
  onLoaded,
  latitude,
  longtitude,
  ...props
}: Props) {
  const { mapIsLoaded, getNaverMap } = useNaverMap();
  const markerDiv = useRef(null);
  const [marker, setMarker] = useState<naver.maps.Marker>();

  const useInitMarker = () => {
    if (!markerDiv.current) return;

    const init = new window.naver.maps.Marker({
      map: getNaverMap,
      position: new window.naver.maps.LatLng(latitude, longtitude),
      icon: children
        ? {
            content: markerDiv.current,
          }
        : undefined,
    });
    setMarker(init);
    onLoaded && onLoaded(init);
  };

  useEffect(() => {
    if (!mapIsLoaded) return;
    useInitMarker();

    return () => {
      marker?.setMap(null);
      setMarker(undefined);
    };
  }, [mapIsLoaded]);
  return (
    <div style={{ display: "none" }}>
      <div ref={markerDiv} {...props}>
        {children}
      </div>
    </div>
  );
}
