// apps/vue/src/components/Marker.vue
<script lang="ts" setup>
import { useNaverMap } from "../composables/useNaverMap";
import { ref, useAttrs, watch } from "vue";

const emits = defineEmits<{
  (event: "onLoaded", marker: naver.maps.Marker): void;
}>();
const props = defineProps<{
  latitude: number;
  longitude: number;
  htmlIcon?: naver.maps.HtmlIcon;
}>();

const attrs = useAttrs();
const { getNaverMap } = useNaverMap();
const { mapIsLoaded, map } = getNaverMap();

const marker = ref<naver.maps.Marker>();
const markerRef = ref<HTMLDivElement>();

const getMarkerIcon = () => {
  if (!markerRef.value?.childElementCount) return undefined; // default marker
  return Object.assign({ content: markerRef.value }, props.htmlIcon ?? {});
};
const handleCreateMarker = () => {
  if (!markerRef.value) throw new Error("marker ref is not founded");
  marker.value = new naver.maps.Marker({
    position: new naver.maps.LatLng(props.latitude, props.longitude),
    map: map?.value,
    icon: getMarkerIcon(),
  });
  emits("onLoaded", marker.value);
};

watch(
  () => mapIsLoaded?.value,
  (newVal) => {
    if (!newVal) return;
    handleCreateMarker();
  },
);
</script>

<template>
  <div style="display: none">
    <div ref="markerRef" v-bind="attrs">
      <slot />
    </div>
  </div>
</template>

// apps/react/src/components/Marker.tsx
import { useNaverMap } from "@/hooks/useNaverMap";
import {
  useRef,
  type HTMLAttributes,
  type PropsWithChildren,
  useState,
  useEffect,
} from "react";

interface Props extends HTMLAttributes<HTMLDivElement> {
  onLoaded?: (marker: naver.maps.Marker) => void;
  latitude: number;
  longitude: number;
}

export default function Marker({
  onLoaded,
  latitude,
  longitude,
  children,
  ...props
}: PropsWithChildren<Props>) {
  const ref = useRef<HTMLDivElement>(null);
  const [marker, setMarker] = useState<naver.maps.Marker>();
  const { map, mapIsLoaded } = useNaverMap();

  const handleCreateMarker = (map: naver.maps.Map) => {
    if (!ref.current) throw new Error("marker ref is not founded");

    const markerInstance = new naver.maps.Marker({
      map,
      position: new naver.maps.LatLng(latitude, longitude),
      icon: children
        ? {
            content: ref.current,
          }
        : undefined,
    });
    setMarker(() => markerInstance);
    onLoaded && onLoaded(markerInstance);
  };

  useEffect(() => {
    if (mapIsLoaded && map) handleCreateMarker(map);
  }, [mapIsLoaded]);

  useEffect(() => {
    return () => {
      marker?.setMap(null);
      setMarker(() => undefined);
    };
  }, []);

  return (
    <div style={{ display: "none" }}>
      <div ref={ref} {...props}>
        {children}
      </div>
    </div>
  );
}
