// apps/react/src/components/Map.component.tsx
import { useEffect, useRef, useState } from "react";
import { useNaverMapScript, useMap } from "utils";
import { NaverMapContext } from "@/hooks/useNaverMap";

import type { Layers, MapOptions } from "types";
import type { PropsWithChildren, HTMLAttributes } from "react";

interface Props extends PropsWithChildren, HTMLAttributes<HTMLDivElement> {
  onLoaded?: (map: naver.maps.Map) => void;
  initLayers?: Layers[];
  mapOptions?: MapOptions;
}

export default function Map({
  children,
  initLayers,
  mapOptions,
  onLoaded,
  ...props
}: Props) {
  const { getMapSettings } = useMap();
  const { callbackAfterScriptLoaded } = useNaverMapScript();
  const mapDiv = useRef(null);
  const [navermap, setNaverMap] = useState<naver.maps.Map>();

  const useInitMap = () => {
    if (!mapDiv.current) return;

    const init = new window.naver.maps.Map(
      mapDiv.current,
      getMapSettings(mapOptions, initLayers)
    );
    setNaverMap(init);
    onLoaded && onLoaded(init);
  };

  useEffect(() => {
    window.naver ? useInitMap() : callbackAfterScriptLoaded(useInitMap);

    return () => {
      navermap?.destroy();
      setNaverMap(undefined);
    };
  }, []);

  return (
    <NaverMapContext.Provider value={navermap}>
      <div ref={mapDiv} {...props}>
        {children}
      </div>
    </NaverMapContext.Provider>
  );
}

// apps/vue/src/components/Map.vue
<script lang="ts" setup>
import { onMounted, onUnmounted, ref } from "vue";
import { handleInstallScript, getMapSettings } from "utils";
import { useNaverMap } from "../composables/useNaverMap";
import type { Layers, MapOptions, InstallOptions } from "types";

const emits = defineEmits<{
  (event: "onLoaded", map: naver.maps.Map): void;
}>();
const props = defineProps<
  {
    mapOptions?: MapOptions;
    initLayers?: Layers[];
  } & InstallOptions
>();

const map = ref<naver.maps.Map>();
const mapIsLoaded = ref(false);
const mapRef = ref<HTMLDivElement>();
const { setNaverMap } = useNaverMap();

setNaverMap({
  map,
  mapIsLoaded,
});

const handleCreateMap = () => {
  if (!mapRef.value) throw new Error("map ref is not founded");
  map.value = new naver.maps.Map(
    mapRef.value,
    getMapSettings(props.mapOptions, props.initLayers),
  );
  mapIsLoaded.value = true;
  emits("onLoaded", map.value);
};

onMounted(() => {
  handleInstallScript({
    clientId: props.clientId,
    subModules: props.subModules,
    category: props.category,
    callback: [handleCreateMap],
  });
});

onUnmounted(() => {
  map.value?.destroy();
  map.value = undefined;
});
</script>

<template>
  <div ref="mapRef">
    <slot />
  </div>
</template>
