// apps/react/src/components/Map.tsx
import {
  useState,
  type PropsWithChildren,
  useEffect,
  useRef,
  type HtmlHTMLAttributes,
} from "react";
import type { InstallOptions, Layers, MapOptions } from "types";
import { getMapSettings, handleInstallScript } from "utils";
import { NaverMapContext } from "@/stores";

interface Props extends InstallOptions, HtmlHTMLAttributes<HTMLDivElement> {
  mapOptions?: MapOptions;
  initLayers?: Layers[];
  onLoaded?: (map: naver.maps.Map) => void;
}

export default function Map({
  clientId,
  category,
  subModules,
  initLayers,
  mapOptions,
  onLoaded,
  children,
  ...props
}: PropsWithChildren<Props>) {
  const ref = useRef<HTMLDivElement>(null);
  const [mapIsLoaded, setMapIsLoaded] = useState(false);
  const [map, setMap] = useState<naver.maps.Map>();
  const options = { clientId, category, subModules };

  const handleCreateMap = () => {
    if (!ref.current) throw new Error("map ref is not founded");
    const mapInstance = new naver.maps.Map(
      ref.current,
      getMapSettings(mapOptions, initLayers),
    );
    setMap(() => mapInstance);
    setMapIsLoaded(() => true);

    onLoaded && onLoaded(mapInstance);
  };

  useEffect(() => {
    handleInstallScript({
      ...options,
      callback: [handleCreateMap],
    });

    return () => {
      map?.destroy();
      setMap(() => undefined);
    };
  }, []);

  return (
    <NaverMapContext.Provider value={{ map, mapIsLoaded }}>
      <div ref={ref} {...props}>
        {children}
      </div>
    </NaverMapContext.Provider>
  );
}

// apps/vue/src/components/Map.vue
<script lang="ts" setup>
import { onMounted, onUnmounted, ref } from "vue";
import { handleInstallScript, getMapSettings } from "utils";
import { useNaverMap } from "../composables/useNaverMap";
import type { Layers, MapOptions, InstallOptions } from "types";

const emits = defineEmits<{
  (event: "onLoaded", map: naver.maps.Map): void;
}>();
const props = defineProps<
  {
    mapOptions?: MapOptions;
    initLayers?: Layers[];
  } & InstallOptions
>();

const map = ref<naver.maps.Map>();
const mapIsLoaded = ref(false);
const mapRef = ref<HTMLDivElement>();
const { setNaverMap } = useNaverMap();

setNaverMap({
  map,
  mapIsLoaded,
});

const handleCreateMap = () => {
  if (!mapRef.value) throw new Error("map ref is not founded");
  map.value = new naver.maps.Map(
    mapRef.value,
    getMapSettings(props.mapOptions, props.initLayers),
  );
  mapIsLoaded.value = true;
  emits("onLoaded", map.value);
};

onMounted(() => {
  handleInstallScript({
    clientId: props.clientId,
    subModules: props.subModules,
    category: props.category,
    callback: [handleCreateMap],
  });
});

onUnmounted(() => {
  map.value?.destroy();
  map.value = undefined;
});
</script>

<template>
  <div ref="mapRef">
    <slot />
  </div>
</template>
